Repository agustinanisaf/SquareCheck-android, pull requests merged in 2020-12, with the labels that each got.

#56 Show Student Toolbar Menu
  app/src/main/java/com/squarecheck/base/view/BaseFragment.java
  app/src/main/java/com/squarecheck/base/view/BaseFragmentHolderActivity.java
  app/src/main/java/com/squarecheck/base/view/FragmentListener.java
  app/src/main/java/com/squarecheck/shared/callback/RetrofitCallback.java
  app/src/main/java/com/squarecheck/student/adapter/StudentAttendanceSummaryRecyclerViewAdapter.java
  app/src/main/java/com/squarecheck/student/contract/StudentDashboardContract.java
  app/src/main/java/com/squarecheck/student/interactor/StudentDashboardInteractor.java
  app/src/main/java/com/squarecheck/student/presenter/StudentDashboardPresenter.java
  app/src/main/java/com/squarecheck/student/view/StudentDashboardActivity.java
  app/src/main/java/com/squarecheck/student/view/StudentDashboardFragment.java
  app/src/main/res/layout/activity_base.xml
  app/src/main/res/layout/dashboard_attendance_toolbar.xml
  app/src/main/res/layout/dashboard_summary_toolbar.xml
Labels: android, enhancement, ui

#59 Fix Both User's Toolbar
  app/src/main/java/com/squarecheck/lecturer/contract/LecturerDashboardContract.java
  app/src/main/java/com/squarecheck/lecturer/interactor/LecturerDashboardInteractor.java
  app/src/main/java/com/squarecheck/lecturer/presenter/LecturerDashboardPresenter.java
  app/src/main/java/com/squarecheck/lecturer/view/LecturerDashboardFragment.java
  app/src/main/java/com/squarecheck/student/contract/StudentDashboardContract.java
  app/src/main/java/com/squarecheck/student/interactor/StudentDashboardInteractor.java
  app/src/main/java/com/squarecheck/student/presenter/StudentDashboardPresenter.java
  app/src/main/java/com/squarecheck/student/view/StudentDashboardFragment.java
  app/src/main/res/drawable/default_profile.xml
  app/src/main/res/layout/activity_base.xml
  app/src/main/res/layout/student_dashboard_toolbar.xml
Labels: android, enhancement, ui

#52 Create Student Notification Activity
  .idea/codeStyles/Project.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/squarecheck/student/contract/StudentAttendanceNotificationContract.java
  app/src/main/java/com/squarecheck/student/contract/StudentDashboardContract.java
  app/src/main/java/com/squarecheck/student/interactor/StudentDashboardInteractor.java
  app/src/main/java/com/squarecheck/student/model/NotificationPresenceItem.java
  app/src/main/java/com/squarecheck/student/presenter/StudentAttendanceNotificationPresenter.java
  app/src/main/java/com/squarecheck/student/presenter/StudentDashboardPresenter.java
  app/src/main/java/com/squarecheck/student/view/StudentAttendanceNotificationActivity.java
  app/src/main/java/com/squarecheck/student/view/StudentAttendanceNotificationFragment.java
  app/src/main/java/com/squarecheck/student/view/StudentDashboardFragment.java
  app/src/main/res/layout/content_notification.xml
Labels: android, enhancement

#61 Retrofit Multiple Logger
  app/src/main/java/com/squarecheck/shared/retrofit/JWTAuthenticationInterceptor.java
  app/src/main/java/com/squarecheck/shared/retrofit/ServiceGenerator.java
Labels: android, bug
